spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 480686846664-dujgnhn65pt32m4umto4jumsr9kolfol.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true